[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_extra_dirs =
  ../SOZO-Common/lib

monitor_speed = 115200
upload_port = COM19
monitor_port = COM19
upload_speed = 921600

board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv

; ESP32-S3-WROOM-1-N8R8: QIO Flash + OPI PSRAM.
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=4
  -DCONFIG_BT_NIMBLE_MAX_BONDS=4
  -DCONFIG_BT_NIMBLE_MAX_CCCDS=8

lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0
  https://github.com/h2zero/NimBLE-Arduino.git#2.5.0
