[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = COM9
monitor_port = COM9
lib_extra_dirs =
  ../SOZO-Common/lib
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DSOZO_NODE_LED_PIN=4
  -DSOZO_NODE_MAX_LED_COUNT=512
  -DSOZO_NODE_DEFAULT_LED_COUNT=60
  -DSOZO_NODE_BOOT_PIN=9
lib_deps =
  fastled/FastLED@3.10.3
  https://github.com/h2zero/NimBLE-Arduino.git#2.5.0
